<!DOCTYPE html>
<html lang="en">
<head>
    <title>University Clubs Activities</title>
    <link rel="stylesheet" type="text/css" href="activityStyle.css">
</head>
<body>
   <header>
    <div class="header-left">
        <a href="index.html">
            <img src="logo1.svg" alt="logo" class="logo1">
        </a>
    </div>
    <h1>University Clubs Activities</h1>
</header>


    <div class="search-filter">
        <input type="text" id="search" placeholder="Search for an activity...">
        <select id="category">
            <option value="all">All Categories</option>
            <option value="sports">Sports</option>
            <option value="arts">Arts</option>
            <option value="technology">Technology</option>
			 <option value="science">Science</option>
            <option value="literature">Literature</option>
        </select>
        <button>Filter</button>
    </div>

    <div class="activities-list">
        <div class="activity football">
            <h2>Football Tournament</h2>
            <p class="club">Organized by: Sports Club</p>
			<p class="club1">categories: sport</p>
            <p class="description">Join our exciting football tournament and compete with the best!</p>
            <a href="details.html" class="details">View Details</a>

        </div>

        <div class="activity photography">
            <h2>Photography Workshop</h2>
            <p class="club">Organized by: Arts Club</p>
			 <p class="club1">categories: Art</p>
            <p class="description">Learn professional photography techniques from experts.</p>
            <a href="details.html" class="details">View Details</a>
        </div>

        <div class="activity coding">
            <h2>Coding Bootcamp</h2>
            <p class="club">Organized by: Tech Club</p>
			<p class="club1">categories: technology</p>
            <p class="description">Enhance your programming skills with hands-on coding sessions.</p>
            <a href="activity_details.html" class="details">View Details</a>
           
        </div>
		
		<div class="activity robotics">
            <h2>Robotics Challenge</h2>
            <p class="club">Organized by: Science Club</p>
			<p class="club1">categories: technology</p>
            <p class="description">Build and program your own robot to complete exciting challenges.</p>
            <a href="details.html" class="details">View Details</a>
        </div>

        <div class="activity creative">
            <h2>Creative Writing Contest</h2>
            <p class="club">Organized by: Literature Club</p>
			<p class="club1">categories: Literature</p>
            <p class="description">Unleash your creativity and participate in our annual writing contest.</p>
            <a href="details.html" class="details">View Details</a>
        </div>

        <div class="activity chess">
            <h2>Chess Championship</h2>
            <p class="club">Organized by: Mind Games Club</p>
			<p class="club1">categories: sport</p>
            <p class="description">Compete in our chess tournament and prove your strategic thinking skills.</p>
            <a href="details.html" class="details">View Details</a>
        </div>
		
    </div>
	
	<footer class="footer">
        <div class="footer-container">
             <!-- قسم يحتوي على الشعار -->
           <div class="footer-section4">
		    <a href="student_page.html">
            <img src="logo1.svg" alt="Logo" class="footer-logo">
			</a>
            </div>


            <div class="footer-section1">
                <h4>Colleges</h4>
                <ul class="footer-menu">
                    <li><a href="/en/colleges/health" title="Health">Health</a></li>
                    <li><a href="/en/colleges/engineering" title="Engineering">Engineering</a></li>
                    <li><a href="/en/colleges/sciences" title="Sciences and Management">Sciences and Management</a></li>
                    <li><a href="/en/colleges/arts" title="Arts and Education">Arts and Education</a></li>
                    <li><a href="/en/colleges/social-sciences" title="Social Sciences">Social Sciences</a></li>
                </ul>
            </div>
        
            <div class="footer-section2">
                <h4>Contact Us</h4>
                <div class="social-icons">
                    <a href="https://facebook.com" title="Facebook">
                        <img src="facebook.svg" alt="Facebook">
                    </a>

                    <a href="https://instagram.com" title="instagram">
                        <img src="instagram.svg" alt="instagram">
                    </a>
                    <a href="https://linkedin.com" title="linkedin">
                        <img src="linkedin.svg" alt="linkedin">
                    </a>
                    <a href="https://x.com" title="x" class="x-icon">
                        <img src="x.svg" alt="x">
                    </a> 
                    <a href="https://whatsapp.com" title="whatsApp">
                        <img src="whatsapp.svg" alt="whatsApp">
                    </a>
                </div>
            </div>
        
            <div class="footer-section3">
                <h4>Our Location</h4>
                <div class="footer-map">
                    <iframe  src="https://www.google.com/maps/embed?pb=!1m26!1m12!1m3!1d231895.03167743672!2d46.86497690758214!3d24.748847541634948!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m11!3e6!4m3!3m2!1d24.7660706!2d46.8156074!4m5!1s0x3e2f1d7da06f1b67%3A0x6706faf0b2570bfc!2z2KzYp9mF2LnYqSDYp9mE2YXZhNmDINiz2LnZiNiv2Iwg2KfZhNix2YrYp9i2IDExNDUx4oCt!3m2!1d24.7227575!2d46.622575499999996!5e0!3m2!1sar!2ssa!4v1739529002212!5m2!1sar!2ssa" width="100" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
            </div>

        </div>
        <!-- الخط الأفقى -->
        <div class="footer-line"></div>
    
        <!-- النصوص الصغيرة في الفوتر -->
        <div class="footer-smallprint">
            <span class="footer-left">© 2025 CLUBSPHERE. All rights reserved.</span>
            <span class="footer-right">Last update on: February 13, 2025 - 12:12 pm</span>
        </div>
    </footer>
</body>
</html>
